apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
    spec:
      containers:
      - name: calculator-api
        image: gcr.io/alpine-zodiac-445418-m6/calculator-api
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-api-service
spec:
  type: NodePort
  selector:
    app: calculator-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
